### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (3 given)

### ISSUE THREAD

**Issue by wojtulab** [adafruit/Adafruit_Python_SSD1306#15] opened 2017-04-26 21:53 UTC
Hello,
I have following issue on RBPI:

```
pi@RBPI:~/apps/OLED/python-examples $ sudo python OLEDclock.py
Traceback (most recent call last):
  File "OLEDclock.py", line 18, in <module>
    led = gaugette.ssd1306.SSD1306(reset_pin=RESET_PIN, dc_pin=DC_PIN)
TypeError: __init__() takes at least 3 arguments (3 given)
```

![image](https://cloud.githubusercontent.com/assets/14801148/25471328/e3d440a4-2b26-11e7-82a5-94dad589ab2e.png)

line 11: (yellow highlighted)
![image](https://cloud.githubusercontent.com/assets/14801148/25471514/bc6ac294-2b27-11e7-9050-555bb4f7baf5.png)

OS:
Linux RBPI 4.4.21-v7+ #911 SMP Thu Sep 15 14:22:38 BST 2016 armv7l GNU/Linux with Python 2.7.9

**Comment by wojtulab** [comment] 2017-05-07 18:29
any feedback, help or hint?

**Comment by Vilhjalmr26** [comment] 2017-05-28 01:09
you should be creating an item of the typ eof display you have, so ssd1306.SSD1306_128_64 or ssd1306.SSD1306_128_32.  That may help.

**Comment by wojtulab** [comment] 2017-06-03 18:27
ok i see. I will try it and back to U.

**Comment by wojtulab** [comment] 2017-06-07 06:10
hello, another issue:
![image](https://user-images.githubusercontent.com/14801148/26864510-cf6f618c-4b58-11e7-8bc3-629630e2321c.png)

**Comment by Vilhjalmr26** [comment] 2017-06-07 06:37
Sorry, missed this earlier. For using this library I would expect your import to be
import Adafruit_SSD1306
Not
import gaugette.ssd1306
Unless you have a different setup

**Comment by wojtulab** [comment] 2017-06-08 08:39
changed to
![image](https://user-images.githubusercontent.com/14801148/26919652-bb355ab2-4c36-11e7-8107-3b91e9c057c1.png)

another issue:
![image](https://user-images.githubusercontent.com/14801148/26919687-cd8441b0-4c36-11e7-9a9e-6454bdf1655a.png)

**Comment by wojtulab** [comment] 2017-06-12 09:18
any updates?

**Comment by Vilhjalmr26** [comment] 2017-06-12 14:08
Sorry, not seeing what the issue is here

**Comment by wojtulab** [comment] 2017-06-12 14:45
what do you mean?

this is my error:
![image](https://user-images.githubusercontent.com/14801148/27039562-89d2baae-4f8e-11e7-8e34-288bcd6a1eeb.png)



my full config is:
![image](https://user-images.githubusercontent.com/14801148/27039576-977048c0-4f8e-11e7-93b0-ac8e018b87e3.png)

**Comment by Vilhjalmr26** [comment] 2017-06-12 15:39
Sorry, my email hid the second image in the original request, hence my
confusion.
reset_pin should instead be rst, dc_pin should instead be dc
I suggest looking in the examples folder at the shapes.py file, it sets
everything up for a basic display, and you can modify from there.

**Comment by wojtulab** [comment] 2017-06-13 06:53
ok, changed to:
led = Adafruit_SSD1306.SSD1306_128_64(rst=RESET_PIN, dc=DC_PIN)

and another issue:
pi@RBPI:~/apps/Adafruit_Python_SSD1306/examples $ sudo python OLEDclock.py
Traceback (most recent call last):
  File "OLEDclock.py", line 14, in <module>
    led.begin()
  File "build/bdist.linux-armv7l/egg/Adafruit_SSD1306/SSD1306.py", line 147, in begin
  File "build/bdist.linux-armv7l/egg/Adafruit_SSD1306/SSD1306.py", line 244, in _initialize
  File "build/bdist.linux-armv7l/egg/Adafruit_SSD1306/SSD1306.py", line 128, in command
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_GPIO-1.0.0-py2.7.egg/Adafruit_GPIO/I2C.py", line 114, in write8
  File "/usr/local/lib/python2.7/dist-packages/Adafruit_PureIO-0.2.0-py2.7.egg/Adafruit_PureIO/smbus.py", line 236, in write_byte_data
IOError: [Errno 5] Input/output error

![image](https://user-images.githubusercontent.com/14801148/27069572-b4bacb4e-5015-11e7-9b2b-fd40c20a9ac6.png)

**Comment by ladyada** [comment] 2017-06-13 16:08
hiya we're going to close this issue because it seems to be a tech support thread not software related. thx :)

**Closed by ladyada** 2017-06-13 16:08 UTC

**Comment by wojtulab** [comment] 2017-06-13 18:21
ok i see, sorry for that

**Comment by sydneykcho** [comment] 2019-02-12 12:05
I faced the same issue as above case when running with Beaglebone Black.
If it be classified as a tech support thread, but it occurred on different platform and devices?
